name: api-sample

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE: leel2415/api-sample
  VERSION: ${{ github.sha }}
  NAME: api-sample


jobs:        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
      
  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Docker run
        run: |
          docker ps -q --filter "name=${{ env.NAME }}" | grep -q . && docker stop ${{ env.NAME }} && docker rm -fv ${{ env.NAME }}
          docker run -d -p 8090:8090 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
